service: ease-form-email-sender

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  logRetentionInDays: 3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource:
        - "*"
  environment:
    TO: ${file(./env.json):TO, env:TO}
    FROM: ${file(./env.json):FROM, env:FROM}

functions:
  sendEmail:
    handler: handler.send
    events:
      - http:
          path: form-api/sendform
          method: post
package:
  exclude:
    - src/tests/**
    - jest.config.js
    - tsconfig.json
    - tslint.json
    - env*.json
    - .travis.yml
    - .prettierrc
