service: ease-form-email-sender

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  logRetentionInDays: 3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource:
        - "*"
  environment:
    TO: ${file(./env.json):TO}
    FROM: ${file(./env.json):FROM}

functions:
  sendEmail:
    handler: handler.send
    events:
      - http:
          path: form-api/sendform
          method: post
